export const FAQ = {
  greeting: '¡Hola! 👋 Gracias por comunicarse al consultorio del Dr. Cristopher González, Neurocirugía y Cirugía de Columna. ¿En qué podemos ayudarle?',
  consultorios: 'Contamos con dos consultorios:\n\n*Hospital México Americano*, en Guadalajara.\n*Hospital San Serafín*, en La Tijera, al sur de la ciudad.\n\n¿En cuál de los dos le gustaría que revisemos disponibilidad?',
  regularPrice: 'La consulta regular tiene un costo de *$800*. El pago puede realizarse en efectivo, transferencia, tarjeta de débito o tarjeta de crédito.',
  fbFirstPrice: 'La primera consulta con la promoción tiene un costo de *$400*.',
  fbFollowupPrice: 'En las consultas subsecuentes del esquema promocional el costo es de *$600*.',
  previousRegularNoPromo: 'Gracias por contactarnos. La promoción está disponible para pacientes de primera vez. Como ya contamos con un registro previo de atención en el consultorio, en este caso la consulta corresponde a la tarifa regular de *$800*. Con gusto podemos revisar los horarios disponibles para su próxima cita.',
  mexicoLocation: '*Hospital México Americano*\nPiso 2, Consultorio 215\nCalle Colomos 2110, Colonia Ayuntamiento. Guadalajara, Jalisco. CP 44620\nUbicación: https://share.google/hXKcNqtqVPQnoUtYt',
  sanSerafinLocation: '*Hospital San Serafín*\nCallejón 6 de Mayo #3, La Tijera. Tlajomulco de Zúñiga, Jalisco. CP 45647\nUbicación: https://share.google/RHsKah2QMWV9F3vHU',
  insurance: 'Actualmente contamos con convenio con múltiples aseguradoras y nos ajustamos a los tabuladores de la mayoría de ellas. Si nos indica cuál es su aseguradora, podemos revisar su caso.',
  whatToBring: 'Para una adecuada valoración es importante acudir con todos los estudios que ya le hayan realizado, como radiografías, tomografías, resonancia magnética, estudios de laboratorio u otros estudios relacionados con su padecimiento. También es conveniente llevar los medicamentos que consume actualmente y las recetas o indicaciones previas que le hayan otorgado.',
  surgeryPrice: 'El costo estimado depende específicamente del padecimiento, el procedimiento requerido, el hospital y los materiales que puedan necesitarse. El presupuesto puede establecerse una vez que el doctor conozca al paciente y valore su caso.',
  human: 'Claro. ¿Podría indicarnos brevemente en qué podemos ayudarle para poder canalizar su mensaje?',
  doctor: 'Permítame un momento para comentarle la situación al doctor y poder resolver su situación.',
  urgentAppointment: 'Entiendo. Permítame un momento para revisar personalmente la posibilidad de atenderle lo antes posible.',
  emergency: 'Por los síntomas que nos comenta, es importante que el paciente sea valorado *de forma inmediata en un servicio de Urgencias* y no esperar a una consulta programada.',
  referredPromo: 'Claro. ¿Podría indicarnos el nombre de la persona que le compartió la promoción?',
  verifyPromo: 'Gracias. Permítame verificar la información para confirmar que la promoción aplique correctamente.',
  askName: 'Para continuar, ¿podría indicarnos el *nombre completo del paciente*?',
  askReason: '¿Podría comentarnos brevemente cuál es el motivo de la consulta?',
  noAvailability: 'Por el momento no encontramos espacios disponibles dentro del periodo solicitado. Si gusta, podemos revisar fechas posteriores.',
  conditionClear: 'Sí, el Dr. González atiende este tipo de padecimientos dentro de Neurocirugía y Cirugía de Columna. Si gusta, podemos revisar los próximos horarios disponibles para valoración.',
  conditionInitial: 'Sí podemos realizar una valoración inicial para revisar su caso, exploración y estudios previos y determinar el manejo más adecuado. Si gusta, podemos consultar disponibilidad.',
  unknown: 'Permítame verificar esa información para darle una respuesta correcta.'
};
